// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;
import 'package:firebase_messaging/firebase_messaging.dart';


Future<void> initializeFirebase() async {
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  try {
    final fcmToken = await FirebaseMessaging.instance.getToken();
    if (fcmToken != null) {
      print('FCM Token: $fcmToken');
      // Send the token to your server
    } else {
      print('Failed to get FCM token');
    }
  } catch (e) {
    print('Error fetching FCM token: $e');
  }
}

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCApFUKN-rQ7sNe2cCjzzLqhyJPHlrJIpg',
    appId: '1:1034011063618:web:e63196a80c449eca6084db',
    messagingSenderId: '1034011063618',
    projectId: 'userandroid-888ec',
    authDomain: 'userandroid-888ec.firebaseapp.com',
    storageBucket: 'userandroid-888ec.appspot.com',
    measurementId: 'G-JLCN87VYM1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJLv1G-U0plS_164CejHR2rlbHJ8mWQ58',
    appId: '1:1034011063618:android:e78cee53426d08586084db',
    messagingSenderId: '1034011063618',
    projectId: 'userandroid-888ec',
    storageBucket: 'userandroid-888ec.appspot.com',
  );

}